name: "On Push master"
triggers:
  github:
    secret: test
    events:
      - eventName: "push"
env:
  name: Heimanba
  age: 31
steps:
  - run: echo 'Hi {{ env.name }}'  # Hi Heimanba
  - run: echo 'Hi {{ env.name }}'  # Hi Tony
    env:
      name: Tony
  - run: echo 'Hi {{ task_id }}'
  - run: echo 'Hi {{ app.user_name }}'
  - run: echo 'Hi {{ git.event_name }}'
  - run: echo 'test' >> test.txt
    path: './'
  - run: pwd
  - run: ls -al
  - run: echo '${{env.name}}-${{hashFile("./test.txt")}}'

  
